[versions]
agp = "9.0.0"
kotlin = "2.3.0"
ksp = "2.3.2"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.2"
constraintlayout = "2.2.1"
trixnity = "5.0.1"
lognity = "1.2.1"
ktor = "3.3.3"
kotlinx-serialization-json = "1.9.0"
recyclerviewbuilder = "1.0.1"
navigationRuntimeKtx = "2.9.6"
navigationFragmentKtx = "2.9.6"
glide = "4.16.0"
overlappingpanels = "0.1.5"
mentionsedittext = "1.0.1"
google-services = "4.4.4"
firebase-bom = "34.8.0"
emoji2 = "1.6.0"
hilt = "2.58"
commonmark = "0.27.1"
avatarview = "1.0.7"
jsoup = "1.22.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
trixnity-client = { group = "de.connect2x.trixnity", name = "trixnity-client", version.ref = "trixnity" }
trixnity-client-repository-room = { group = "de.connect2x.trixnity", name = "trixnity-client-repository-room", version.ref = "trixnity" }
trixnity-client-media-okio = { group = "de.connect2x.trixnity", name = "trixnity-client-media-okio", version.ref = "trixnity" }
trixnity-client-cryptodriver-vodozemac = { group = "de.connect2x.trixnity", name = "trixnity-client-cryptodriver-vodozemac", version.ref = "trixnity" }
lognity-api-android = { group = "de.connect2x.lognity", name = "lognity-api-android", version.ref = "lognity" }
lognity-core-android = { group = "de.connect2x.lognity", name = "lognity-core-android", version.ref = "lognity" }
ktor = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-resources = { group = "io.ktor", name = "ktor-resources", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
recyclerviewbuilder = { group = "com.github.kuylar", name = "RecyclerViewBuilder", version.ref = "recyclerviewbuilder" }
androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigationRuntimeKtx" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-compiler = { group = "com.github.bumptech.glide", name = "ksp", version.ref = "glide" }
overlappingpanels = { group = "com.github.discord", name = "OverlappingPanels", version.ref = "overlappingpanels" }
mentionsedittext = { group = "com.github.kuylar", name = "MentionsEditText", version.ref = "mentionsedittext" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging" }
emoji2 = { group = "androidx.emoji2", name = "emoji2", version.ref = "emoji2" }
dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
commonmark = { group = "org.commonmark", name = "commonmark", version.ref = "commonmark" }
commonmark-ext-gfm-tables = { group = "org.commonmark", name = "commonmark-ext-gfm-tables", version.ref = "commonmark" }
commonmark-ext-gfm-strikethrough = { group = "org.commonmark", name = "commonmark-ext-gfm-strikethrough", version.ref = "commonmark" }
commonmark-ext-autolink = { group = "org.commonmark", name = "commonmark-ext-autolink", version.ref = "commonmark" }
commonmark-ext-ins = { group = "org.commonmark", name = "commonmark-ext-ins", version.ref = "commonmark" }
avatarview = { group = "io.getstream", name = "avatarview-glide", version.ref = "avatarview" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
android-library = { id = "com.android.library", version.ref = "agp" }
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
